/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Insets;

public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        util.DBconnection.getConnection();
        
        sifrefield.setText("");
        
        loginTasariminiDuzenle();
    }
    
    private void loginTasariminiDuzenle() {
        Dimension inputBoyutu = new Dimension(180, 30);
        Insets icBosluk = new Insets(5, 8, 5, 8);
        
        // Kutuların boyutlarını mühürleyelim
        kullaniciadifield.setPreferredSize(inputBoyutu);
        sifrefield.setPreferredSize(inputBoyutu);
        jButton1.setPreferredSize(new Dimension(180, 38));
        
        // FlatLaf pürüzsüz iç boşlukları (Padding) ekleyelim
        kullaniciadifield.putClientProperty("JTextField.padding", icBosluk);
        sifrefield.putClientProperty("JTextField.padding", icBosluk);
        
        // Buton ve şifre alanlarını modern Apple (Cupertino) tarzı oval yapıyoruz
        jButton1.putClientProperty("JButton.buttonType", "roundRect");
        kullaniciadifield.putClientProperty("JTextField.placeholderText", "Kullanıcı adınız");
        sifrefield.putClientProperty("JTextField.placeholderText", "Şifreniz");
        
        // Ekran açıldığında monitörün tam ortasında dursun
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kullaniciadifield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sifrefield = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("kullanıcı adı");

        jLabel2.setText("şifre");

        jButton1.setText("giriş");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel4.setText("şifrenizi bilmiyorsanız yöneticinize başvurunuz");

        jLabel3.setText("PERSONEL GİRİŞİ");

        sifrefield.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kullaniciadifield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sifrefield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullaniciadifield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sifrefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    String kullaniciAdi = kullaniciadifield.getText().trim();
    String sifre = new String(sifrefield.getPassword()).trim();

    if (kullaniciAdi.isEmpty() || sifre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Kullanıcı adı ve şifre boş bırakılamaz!",
            "Uyarı",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    dao.kullaniciDAO dao = new dao.kullaniciDAO();
    model.Kullanici kullanici = dao.girisKontrol(kullaniciAdi, sifre);

    if (kullanici == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Kullanıcı adı veya şifre hatalı!",
            "Giriş Başarısız",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        sifrefield.setText("");
        kullaniciadifield.requestFocus();
        return;
    }

    Util.sessionmanager.girisYap(kullanici);
    
    dao.kullaniciDAO kDao = new dao.kullaniciDAO();
    kDao.logKaydet(kullanici);

    main anaPencere = new main();
    anaPencere.setVisible(true);

    this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    
public static void main(String args[]) {
        try {
            // Arka plandaki tüm Nimbus ve eski kalıntıları tamamen bellekten siliyoruz
            javax.swing.UIManager.put("nimbus", null);
            
            // Projenin geneline Apple Cupertino Gecesi Mavisi temasını kuruyoruz
            com.formdev.flatlaf.themes.FlatMacDarkLaf.setup(); 
        } catch (Exception ex) {
            System.err.println("Cupertino Dark tema yüklenirken hata oluştu: " + ex.getMessage());
        }

        /* Formu güvenli bir şekilde sadece login olarak başlatıyoruz */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                login form = new login();
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField kullaniciadifield;
    private javax.swing.JPasswordField sifrefield;
    // End of variables declaration//GEN-END:variables
}
