/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import java.io.File;
import java.awt.Desktop;

public class main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(main.class.getName());

    /**
     * Creates new form main
     */
    public main() {
         initComponents();

    String ad = Util.sessionmanager.getAktifKullanici().getAdSoyad();
    setTitle("KombiServis Pro — " + ad);

    if (!Util.sessionmanager.isAdmin()) {
        jButton5.setVisible(false); 
        raporlarbtn.setVisible(false); 
        silinenbuton.setVisible(false);
    }

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arizakayitbuton = new javax.swing.JButton();
        musterikayitbuton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        raporlarbtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        stokbuton = new javax.swing.JButton();
        contentpanel = new javax.swing.JPanel();
        silinenbuton = new javax.swing.JButton();
        cikisyap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        arizakayitbuton.setText("arıza kaydı oluştur");
        arizakayitbuton.addActionListener(this::arizakayitbutonActionPerformed);

        musterikayitbuton.setText("müşteri kaydı");
        musterikayitbuton.addActionListener(this::musterikayitbutonActionPerformed);

        jButton2.setText("arıza listesi");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        raporlarbtn.setText("raporlar");
        raporlarbtn.addActionListener(this::raporlarbtnActionPerformed);

        jButton5.setText("personel kaydı");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        stokbuton.setText("stok");
        stokbuton.addActionListener(this::stokbutonActionPerformed);

        javax.swing.GroupLayout contentpanelLayout = new javax.swing.GroupLayout(contentpanel);
        contentpanel.setLayout(contentpanelLayout);
        contentpanelLayout.setHorizontalGroup(
            contentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        contentpanelLayout.setVerticalGroup(
            contentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        silinenbuton.setText("silinenler");
        silinenbuton.addActionListener(this::silinenbutonActionPerformed);

        cikisyap.setText("çıkış yap");
        cikisyap.addActionListener(this::cikisyapActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arizakayitbuton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raporlarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musterikayitbuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stokbuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silinenbuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cikisyap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(contentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(arizakayitbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(raporlarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(musterikayitbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stokbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(silinenbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cikisyap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(contentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stokbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokbutonActionPerformed
        stoklar panel = new stoklar();
        sayfaGoster(panel);
    }//GEN-LAST:event_stokbutonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        devamedenarizalar panel = new devamedenarizalar();
        sayfaGoster(panel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void musterikayitbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musterikayitbutonActionPerformed
        musterikayit panel = new musterikayit();
        sayfaGoster(panel);
    }//GEN-LAST:event_musterikayitbutonActionPerformed

    private void arizakayitbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arizakayitbutonActionPerformed

        arizakayit panel = new arizakayit();
        sayfaGoster(panel);
    }//GEN-LAST:event_arizakayitbutonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        personelkayit panel = new personelkayit();
        sayfaGoster(panel);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void silinenbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silinenbutonActionPerformed
        musterigecmis panel = new musterigecmis();
        sayfaGoster(panel);
    }//GEN-LAST:event_silinenbutonActionPerformed

    private void raporlarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raporlarbtnActionPerformed
        String klasorYolu = "C:\\Users\\muham\\OneDrive\\Belgeler\\NetBeansProjects\\kombi\\raporlar";
        File klasor = new File(klasorYolu);

        try {
            if (!klasor.exists()) {
                klasor.mkdirs();
            }

            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                desktop.open(klasor); 
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Sisteminiz otomatik klasör açmayı desteklemiyor.\nKlasör Konumu: " + klasorYolu, 
                    "Sistem Kısıtlaması", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Klasör açılırken bir hata meydana geldi: " + e.getMessage(), 
                "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_raporlarbtnActionPerformed

    private void cikisyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisyapActionPerformed
       int onay = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Oturumu kapatıp giriş ekranına dönmek istediğinize emin misiniz?", 
            "Çıkış Onayı", javax.swing.JOptionPane.YES_NO_OPTION);
       
        if (onay == javax.swing.JOptionPane.YES_OPTION) {
            Util.sessionmanager.cikisYap(); 

            login loginEkrani = new login();
            loginEkrani.setVisible(true);

            this.dispose(); 
        } 
    }//GEN-LAST:event_cikisyapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        com.formdev.flatlaf.themes.FlatMacDarkLaf.setup(); 
    } catch (Exception ex) {
        System.err.println("Cupertino Dark tema yüklenirken hata oluştu!");
    }
    
    java.awt.EventQueue.invokeLater(() -> new main().setVisible(true));
    }
    
    public void sayfaGoster(javax.swing.JPanel yeniPanel) {
    contentpanel.removeAll(); 
    yeniPanel.setSize(contentpanel.getSize()); 
    contentpanel.add(yeniPanel, java.awt.BorderLayout.CENTER); 
    contentpanel.revalidate(); 
    contentpanel.repaint();    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arizakayitbuton;
    private javax.swing.JButton cikisyap;
    private javax.swing.JPanel contentpanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton musterikayitbuton;
    private javax.swing.JButton raporlarbtn;
    private javax.swing.JButton silinenbuton;
    private javax.swing.JButton stokbuton;
    // End of variables declaration//GEN-END:variables
}
