/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import model.Musteri;
import model.Kullanici;
import dao.musteriDAO;
import dao.kullaniciDAO;

public class musterigecmis extends javax.swing.JPanel {

    private musteriDAO mDao = new musteriDAO();
    private kullaniciDAO kDao = new kullaniciDAO();
    
    private int seciliMusteriId = -1;
    
    public musterigecmis() {
        initComponents();
        
        tabloyuDoldur();
    }
    
    public void tabloyuDoldur() {
        musteriTablosunuDoldur();
        personelTablosunuDoldur();
    }

       private void musteriTablosunuDoldur() {
        String[] kolonlar = {"ID", "Ad", "Soyad", "Telefon", "E-mail", "Adres 1", "Adres 2"};
        DefaultTableModel model = new DefaultTableModel(kolonlar, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        try {
            List<Musteri> silinenler = mDao.silinmisMusteriler();

            if (silinenler != null) {
                for (Musteri m : silinenler) {
                    Object[] satir = {
                        m.getId(), 
                        m.getAd(), 
                        m.getSoyad(), 
                        m.getTelefon(), 
                        m.getEmail() == null ? "-" : m.getEmail(), 
                        m.getAdres1() == null ? "-" : m.getAdres1(), 
                        m.getAdres2() == null ? "-" : m.getAdres2() 
                    };
                    model.addRow(satir);
                }
            }
        } catch (Exception e) {
            System.out.println("Müşteri geçmiş tablosu yüklenirken hata: " + e.getMessage());
        }

        jTable1.setModel(model);
    }
       
       private void personelTablosunuDoldur() {
        String[] kolonlar = {"ID", "Ad Soyad", "Kullanıcı Adı", "Ünvan", "T.C. No", "Mezuniyet"};
        DefaultTableModel model = new DefaultTableModel(kolonlar, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        try {
            List<Kullanici> silinenler = kDao.silinmisPersoneller();

            if (silinenler != null) {
                for (Kullanici k : silinenler) {
                    Object[] satir = {
                        k.getId(),
                        k.getAdSoyad(),
                        k.getKullaniciAdi(),
                        k.getRol(),
                        k.getTcNo() == null ? "-" : k.getTcNo(),
                        k.getMezuniyet() == null ? "-" : k.getMezuniyet()
                    };
                    model.addRow(satir);
                }
            }
        } catch (Exception e) {
            System.out.println("Personel geçmiş tablosu yüklenirken hata: " + e.getMessage());
        }

        jTable4.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGeriYukle = new javax.swing.JButton();
        btnTazele = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        silBtn = new javax.swing.JButton();

        btnGeriYukle.setText(" GERİ YÜKLE");
        btnGeriYukle.addActionListener(this::btnGeriYukleActionPerformed);

        btnTazele.setText("LİSTEYİ YENİLE");
        btnTazele.addActionListener(this::btnTazeleActionPerformed);

        jLabel1.setText("MÜŞTERİ GEÇMİŞİ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane2.addTab("müşteriler", jPanel1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("personeller", jPanel2);

        silBtn.setText("SİL");
        silBtn.addActionListener(this::silBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnGeriYukle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnTazele, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(227, 227, 227)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeriYukle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTazele, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeriYukleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriYukleActionPerformed
        int aktifSekme = jTabbedPane2.getSelectedIndex(); 

        if (aktifSekme == 0) {
            int seciliSatir = jTable1.getSelectedRow();
            if (seciliSatir == -1) {
                JOptionPane.showMessageDialog(this, "Lütfen geri yüklemek istediğiniz müşteriyi tablodan seçin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int seciliMusteriId = Integer.parseInt(jTable1.getValueAt(seciliSatir, 0).toString());
            String musteriAdSoyad = jTable1.getValueAt(seciliSatir, 1).toString() + " " + jTable1.getValueAt(seciliSatir, 2).toString();

            int onay = JOptionPane.showConfirmDialog(this, 
                musteriAdSoyad + " isimli müşteriyi tekrar aktif kayıtlar arasına taşımak istiyor musunuz?", 
                "Geri Yükleme Onayı", JOptionPane.YES_NO_OPTION);

            if (onay == JOptionPane.YES_OPTION) {
                if (mDao.geriYukle(seciliMusteriId)) {
                    JOptionPane.showMessageDialog(this, "Müşteri başarıyla geri yüklendi ve aktif listeye eklendi.");
                    tabloyuDoldur(); 
                } else {
                    JOptionPane.showMessageDialog(this, "Geri yükleme işlemi sırasında veritabanı hatası oluştu!", "Hata", JOptionPane.ERROR_MESSAGE);
                }
            }
        } 
        else if (aktifSekme == 1) {
            int seciliSatir = jTable4.getSelectedRow();
            if (seciliSatir == -1) {
                JOptionPane.showMessageDialog(this, "Lütfen işe geri alacağınız personeli tablodan seçin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int seciliPersonelId = Integer.parseInt(jTable4.getValueAt(seciliSatir, 0).toString());
            String personelAdSoyad = jTable4.getValueAt(seciliSatir, 1).toString();

            int onay = JOptionPane.showConfirmDialog(this, 
                personelAdSoyad + " personeli yeniden işe alınsın ve giriş yetkisi aktifleştirilsin mi?", 
                "Personel Geri Yükle", JOptionPane.YES_NO_OPTION);

            if (onay == JOptionPane.YES_OPTION) {
                if (kDao.sil(seciliPersonelId)) { 
                    String sql = "UPDATE kullanici SET durum = 'Aktif' WHERE id = ?";
                    try {
                        java.sql.PreparedStatement ps = util.DBconnection.getConnection().prepareStatement(sql);
                        ps.setInt(1, seciliPersonelId);
                        if (ps.executeUpdate() > 0) {
                            JOptionPane.showMessageDialog(this, "Personel başarıyla işe geri alındı, sisteme giriş yetkisi açıldı.");
                            tabloyuDoldur();
                        }
                    } catch (Exception e) {
                        System.out.println("Geri yükleme SQL hatası: " + e.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGeriYukleActionPerformed

    private void btnTazeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTazeleActionPerformed
        tabloyuDoldur();
        JOptionPane.showMessageDialog(this, "Tüm listeler tazelendi.");
    }//GEN-LAST:event_btnTazeleActionPerformed

    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed
        int aktifSekme = jTabbedPane2.getSelectedIndex(); 

    if (aktifSekme == 0) {
        int seciliSatir = jTable1.getSelectedRow();
        if (seciliSatir == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen kalıcı olarak silmek istediğiniz müşteriyi seçin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(seciliSatir, 0).toString());
        String adSoyad = jTable1.getValueAt(seciliSatir, 1).toString() + " " + jTable1.getValueAt(seciliSatir, 2).toString();

        int onay = JOptionPane.showConfirmDialog(this, 
            "DİKKAT! " + adSoyad + " isimli müşteriyi ve ona ait TÜM ARIZA KAYITLARINI veritabanından kalıcı olarak sileceksiniz.\n" +
            "Bu işlem geri alınamaz! Onaylıyor musunuz?", 
            "GERÇEK SİLME ONAYI", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (onay == JOptionPane.YES_OPTION) {
            if (mDao.kaliciSil(id)) {
                JOptionPane.showMessageDialog(this, "Müşteri ve bağlı verileri SQL'den tamamen yok edildi.");
                tabloyuDoldur(); 
            } else {
                JOptionPane.showMessageDialog(this, "Kalıcı silme sırasında hata oluştu!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    } 
    else if (aktifSekme == 1) {
        int seciliSatir = jTable4.getSelectedRow();
        if (seciliSatir == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen kalıcı olarak silmek istediğiniz personeli seçin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(jTable4.getValueAt(seciliSatir, 0).toString());
        String adSoyad = jTable4.getValueAt(seciliSatir, 1).toString();

        int onay = JOptionPane.showConfirmDialog(this, 
            "DİKKAT! " + adSoyad + " isimli personeli veritabanından kalıcı olarak sileceksiniz.\n" +
            "Bu personelin geçmişte baktığı arıza kayıtları 'Sahipsiz' kalacaktır.\n" +
            "Bu işlem geri alınamaz! Onaylıyor musunuz?", 
            "GERÇEK SİLME ONAYI", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (onay == JOptionPane.YES_OPTION) {
            if (kDao.kaliciSil(id)) {
                JOptionPane.showMessageDialog(this, "Personel kaydı SQL veritabanından kalıcı olarak temizlendi.");
                tabloyuDoldur(); 
            } else {
                JOptionPane.showMessageDialog(this, "Kalıcı silme sırasında hata oluştu!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_silBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeriYukle;
    private javax.swing.JButton btnTazele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton silBtn;
    // End of variables declaration//GEN-END:variables
}
