/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author muham
 */
public class stoklar extends javax.swing.JPanel {

    private int seciliStokId = -1;
    public stoklar() {
        initComponents();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        
        tabloyuDoldur();
    }
    
    public void tabloyuDoldur() {
        String[] kolonlar = {"ID", "Parça İsmi", "Kategori", "Marka", "Model", "Seri No", "Miktar", "Durum"};
        DefaultTableModel model = new DefaultTableModel(kolonlar, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        try {
            dao.stoklarDAO dao = new dao.stoklarDAO();
            List<model.Stok> liste = dao.tumStok();

            if (liste != null) {
                for (model.Stok s : liste) {
                    Object[] satir = {
                        s.getId(),
                        s.getParcaAdi() == null ? "-" : s.getParcaAdi(),
                        s.getKategori(),
                        s.getMarka(),
                        s.getModel(),
                        s.getSeriNo() == null ? "-" : s.getSeriNo(),
                        s.getMiktar(),
                        s.getTedarikci() == null ? "-" : s.getTedarikci() // formdaki durumufield'ı buraya bağlıyoruz
                    };
                    model.addRow(satir);
                }
            }
        } catch (Exception e) {
            System.out.println("Tablo yüklenirken hata oluştu: " + e.getMessage());
        }

        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stokguncellefield = new javax.swing.JTextField();
        mevcutadetfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        guncellebuton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        serinofield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stokmarkasi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stokmodelifield = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        stokserinofield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        durumubox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        parcaguncelleR = new javax.swing.JRadioButton();
        kombiguncelleR = new javax.swing.JRadioButton();
        stokeklebuton = new javax.swing.JButton();
        turparcaR = new javax.swing.JRadioButton();
        turkombiR = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        parcaismifield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        temizlefield = new javax.swing.JButton();
        silbuton = new javax.swing.JButton();
        guncelparcafield = new javax.swing.JTextField();
        guncelmodelfield = new javax.swing.JTextField();
        guncelmarkafield = new javax.swing.JTextField();
        ekledurumubox = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MEVCUT STOK LİSTESİ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 12, -1, -1));

        jLabel11.setText("parça ismi");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 79, -1));

        jLabel7.setText("stok güncelle");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 160, 30));

        jLabel8.setText("adeti güncelle:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 90, -1));

        jLabel12.setText("mevcut adet sayısı:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 176, -1, -1));
        add(stokguncellefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 100, -1));
        add(mevcutadetfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 173, 84, -1));

        jLabel9.setText("seçilen marka:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 87, -1));

        jLabel10.setText("seçilen model:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 78, -1));

        guncellebuton.setText("GÜNCELLE");
        guncellebuton.addActionListener(this::guncellebutonActionPerformed);
        add(guncellebuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 116, 37));

        jLabel13.setText("seri no(opsiyonel)");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, -1, -1));
        add(serinofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 87, -1));

        jLabel14.setText("markası:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 74, -1, -1));
        add(stokmarkasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 71, 104, -1));

        jLabel15.setText("modeli:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 102, -1, -1));
        add(stokmodelifield, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 99, 102, -1));

        jLabel16.setText("seri no:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 136, -1, -1));
        add(stokserinofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 133, 102, -1));

        jLabel17.setText("parçanın / kombinin durumu:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, -1, -1));

        durumubox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sıfır", "sağlam(2.EL)", "arızalı" }));
        add(durumubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, -1, -1));

        jLabel18.setText("durumu:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 228, -1, -1));

        buttonGroup1.add(parcaguncelleR);
        parcaguncelleR.setSelected(true);
        parcaguncelleR.setText("parça");
        add(parcaguncelleR, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, -1, -1));

        buttonGroup1.add(kombiguncelleR);
        kombiguncelleR.setText("kombi");
        add(kombiguncelleR, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, -1, -1));

        stokeklebuton.setText("STOK EKLE");
        stokeklebuton.addActionListener(this::stokeklebutonActionPerformed);
        add(stokeklebuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 389, -1, 59));

        buttonGroup4.add(turparcaR);
        turparcaR.setSelected(true);
        turparcaR.setText("kombi parçası");
        add(turparcaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 301, -1, -1));

        buttonGroup4.add(turkombiR);
        turkombiR.setText("kombi");
        add(turkombiR, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 301, -1, -1));

        jLabel22.setText("türü:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 279, 49, -1));

        jLabel23.setText("parça ismi:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 40, 69, -1));
        add(parcaismifield, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 37, 84, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        temizlefield.setText("TEMİZLE");
        temizlefield.addActionListener(this::temizlefieldActionPerformed);
        add(temizlefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 402, 129, 54));

        silbuton.setText("SİL");
        silbuton.addActionListener(this::silbutonActionPerformed);
        add(silbuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 117, 37));
        add(guncelparcafield, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 97, -1));
        add(guncelmodelfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, 100, -1));
        add(guncelmarkafield, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 180, 106, -1));

        ekledurumubox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sıfır", "sağlam(2.EL)", "arızalı" }));
        add(ekledurumubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 222, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void stokeklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokeklebutonActionPerformed
       String markaVerisi = stokmarkasi.getText().trim();
        String modelVerisi = stokmodelifield.getText().trim();
        String seriNoVerisi = stokserinofield.getText().trim();
        String durumVerisi = ekledurumubox.getSelectedItem().toString();
        String parcaIsmi = parcaismifield.getText().trim();
        
        String kategoriVerisi = turkombiR.isSelected() ? "kombi" : "parca";

        if (markaVerisi.isEmpty() || modelVerisi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Marka ve Model alanları boş bırakılamaz!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int miktarVerisi = 0;
        try {
            miktarVerisi = Integer.parseInt(mevcutadetfield.getText().trim());
            if (miktarVerisi < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lütfen geçerli bir adet sayısı giriniz!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.Stok yeniStok = new model.Stok();
        yeniStok.setMarka(markaVerisi);
        yeniStok.setModel(modelVerisi);
        yeniStok.setSeriNo(seriNoVerisi.isEmpty() ? null : seriNoVerisi);
        yeniStok.setKategori(kategoriVerisi);
        yeniStok.setMiktar(miktarVerisi); 
        yeniStok.setParcaAdi(parcaIsmi.isEmpty() ? (kategoriVerisi + " - " + markaVerisi + " " + modelVerisi) : parcaIsmi);
        yeniStok.setMinStok(0);
        yeniStok.setBirimFiyat(0.0);
        yeniStok.setTedarikci(durumVerisi); 
        int rastgeleSayi = (int)(Math.random() * 9000) + 1000;
        String otomatikKod = "PRK-" + rastgeleSayi;
        yeniStok.setParcaKodu(otomatikKod);

        dao.stoklarDAO dao = new dao.stoklarDAO();
        if (dao.ekle(yeniStok)) {
            JOptionPane.showMessageDialog(this, "Stok veritabanına başarıyla eklendi.");
            tabloyuDoldur(); 
            formuTemizle();
        } else {
            JOptionPane.showMessageDialog(this, "Stok ekleme işlemi başarısız!", "Sistem Hatası", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_stokeklebutonActionPerformed
private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int seciliSatir = jTable1.getSelectedRow();
    if (seciliSatir != -1) {
        this.seciliStokId = Integer.parseInt(jTable1.getValueAt(seciliSatir, 0).toString());
        String parcaAdi = jTable1.getValueAt(seciliSatir, 1).toString();
        String kategori = jTable1.getValueAt(seciliSatir, 2).toString();
        String marka = jTable1.getValueAt(seciliSatir, 3).toString();
        String model = jTable1.getValueAt(seciliSatir, 4).toString();
        String seriNo = jTable1.getValueAt(seciliSatir, 5).toString();
        String miktar = jTable1.getValueAt(seciliSatir, 6).toString();
        String durum = jTable1.getValueAt(seciliSatir, 7).toString();

        parcaismifield.setText(parcaAdi.equals("-") ? "" : parcaAdi);
        stokmarkasi.setText(marka);
        stokmodelifield.setText(model);
        stokserinofield.setText(seriNo.equals("-") ? "" : seriNo);
        mevcutadetfield.setText(miktar);
        if (!durum.equals("-")) {
            ekledurumubox.setSelectedItem(durum);
        } else {
            ekledurumubox.setSelectedIndex(0);
        }

        stokguncellefield.setText(miktar);
        serinofield.setText(seriNo.equals("-") ? "" : seriNo);
        guncelparcafield.setText(parcaAdi.equals("-") ? "" : parcaAdi);
        guncelmodelfield.setText(model.equals("-") ? "" : model);
        guncelmarkafield.setText(marka.equals("-") ? "" : marka);
        
        
        if (!durum.equals("-")) {
            durumubox.setSelectedItem(durum);
        } else {
            durumubox.setSelectedIndex(0);
        }

        if (kategori.equalsIgnoreCase("kombi")) {
            turkombiR.setSelected(true);
            kombiguncelleR.setSelected(true);
        } else {
            turparcaR.setSelected(true);
            parcaguncelleR.setSelected(true);
        }
    }
    }
    private void temizlefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizlefieldActionPerformed
        formuTemizle();
    }//GEN-LAST:event_temizlefieldActionPerformed

    private void silbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silbutonActionPerformed
        if (this.seciliStokId == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen silmek istediğiniz ürünü tablodan seçin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int onay = JOptionPane.showConfirmDialog(this, "Bu stok kaydını tamamen silmek istediğinize emin misiniz?", "Silme Onayı", JOptionPane.YES_NO_OPTION);
        if (onay == JOptionPane.YES_OPTION) {
            dao.stoklarDAO dao = new dao.stoklarDAO();
            if (dao.sil(this.seciliStokId)) {
                JOptionPane.showMessageDialog(this, "Ürün stok listesinden tamamen kaldırıldı.");
                tabloyuDoldur(); 
                formuTemizle();
            } else {
                JOptionPane.showMessageDialog(this, "Silme işlemi sırasında veritabanı hatası oluştu!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_silbutonActionPerformed

    private void guncellebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncellebutonActionPerformed
      if (this.seciliStokId == -1) {
        JOptionPane.showMessageDialog(this, "Lütfen güncelleme yapmak için tablodan bir satır seçin!", "Uyarı", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int yeniMiktar = Integer.parseInt(stokguncellefield.getText().trim());
        if (yeniMiktar < 0) throw new NumberFormatException();
        
        String yeniSeriNo = serinofield.getText().trim();
        String yeniDurum = durumubox.getSelectedItem().toString(); 
        String yeniKategori = kombiguncelleR.isSelected() ? "kombi" : "parca"; 

        dao.stoklarDAO dao = new dao.stoklarDAO();
        if (dao.StokGuncelle(this.seciliStokId, yeniKategori, yeniSeriNo, yeniDurum, yeniMiktar)) {
            JOptionPane.showMessageDialog(this, "Stok bilgileri başarıyla güncellendi.");
            tabloyuDoldur(); 
            formuTemizle();
        } else {
            JOptionPane.showMessageDialog(this, "Güncelleme başarısız oldu.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Lütfen geçerli bir adet sayısı giriniz!", "Hata", JOptionPane.ERROR_MESSAGE);
    }      
    }//GEN-LAST:event_guncellebutonActionPerformed
private void formuTemizle() {
        parcaismifield.setText("");
        stokmarkasi.setText("");
        stokmodelifield.setText("");
        stokserinofield.setText("");
        mevcutadetfield.setText("");
        ekledurumubox.setSelectedIndex(0);
        stokguncellefield.setText("");
        serinofield.setText("");
        this.seciliStokId = -1;
        turparcaR.setSelected(true);
        parcaguncelleR.setSelected(true);
        durumubox.setSelectedIndex(0);
        jTable1.clearSelection();
    }
public void sayfaGoster(javax.swing.JPanel yeniPanel) {
     
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> durumubox;
    private javax.swing.JComboBox<String> ekledurumubox;
    private javax.swing.JButton guncellebuton;
    private javax.swing.JTextField guncelmarkafield;
    private javax.swing.JTextField guncelmodelfield;
    private javax.swing.JTextField guncelparcafield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton kombiguncelleR;
    private javax.swing.JTextField mevcutadetfield;
    private javax.swing.JRadioButton parcaguncelleR;
    private javax.swing.JTextField parcaismifield;
    private javax.swing.JTextField serinofield;
    private javax.swing.JButton silbuton;
    private javax.swing.JButton stokeklebuton;
    private javax.swing.JTextField stokguncellefield;
    private javax.swing.JTextField stokmarkasi;
    private javax.swing.JTextField stokmodelifield;
    private javax.swing.JTextField stokserinofield;
    private javax.swing.JButton temizlefield;
    private javax.swing.JRadioButton turkombiR;
    private javax.swing.JRadioButton turparcaR;
    // End of variables declaration//GEN-END:variables
}
